import { Geist, Geist_Mono, Lateef} from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lateef = Lateef({
  subsets: ['arabic'],
  weight: '400',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lateef.className} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><div className="flex flex-col min-h-screen bg-[var(--primary-color)]"> 
        <main className="flex-1">{children}</main>
        <Footer />
      </div>
      </body>
    </html>
  );
}
